(async function(){
'use strict';
const $=id=>document.getElementById(id),game=new LinkedKing.Adventure(),canvas=$('scene');let renderer,selected=-1,down=-1,previous=0,uiTime=0,visualTime=0,toastUntil=0,lastPhase='',helpPaused=false;
const sources={atlas:'../assets/royal-atlas.png',king:'../assets/king-frames-v4.png',castle:'../assets/castle.png'};const assets={};
try{await Promise.all(Object.entries(sources).map(([key,src])=>new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>{assets[key]=im;resolve();};im.onerror=reject;im.src=src;})));}catch(e){$('loading').textContent='素材加载失败，请刷新重试。';return;}
renderer=new LinkedRenderer(canvas,assets);$('loading').hidden=true;
function toast(s){$('toast').textContent=s;$('toast').classList.add('show');toastUntil=uiTime+2.5;}
function clearSelection(){selected=-1;renderer.selected=-1;renderer.hints=[];}
function hud(){const s=game.stages[game.active];$('chapter').textContent=['walking','transition'].includes(game.phase)?'王室连廊 · 连续前行':s.cfg.label+' · '+s.cfg.name;$('hp').innerHTML=s.hp+' <small>HP</small>';$('health').value=s.hp;$('weight').textContent=s.collected+' / '+(s.cfg.weight+1);$('weight-bar').max=s.cfg.weight+1;$('weight-bar').value=s.collected;$('gate-status').textContent=s.latched?'已升起 · 已锁定':s.gate>0?'正在吊门':'等待积重';$('moves').textContent=s.actions+' 次交换';$('step-a').className=game.stages[0].complete?'done':game.active===0?'active':'';$('step-b').className=game.stages[1].complete?'done':game.active===1?'active':'';
 $('advance').disabled=game.phase!=='playing'||!s.latched||game.paused;$('advance').textContent=s.latched?(game.active===0?'前进 · 穿门前往 B':'前进 · 抵达终点'):s.gate?'正在吊门，请稍候':'积重开门后，可以前进';$('remix').textContent='重排 '+s.remixes;
 for(const id of ['hint','remix'])$(id).disabled=game.phase!=='playing'||game.paused||!!s.op; $('pause').textContent=game.paused?'继续':'暂停';$('pause').disabled=['ready','lost','won'].includes(game.phase);
 $('status').textContent=game.paused?'已暂停：石头、机关和生命停止变化':game.phase==='walking'?'穿过已打开的门，抵达安全落脚点':game.phase==='transition'?'A 已完成 · 沿上层连廊进入 B':game.phase==='won'?'两段救援完成，国王已安全抵达终点':game.phase==='lost'?'HP 已归零，可以重试当前段':s.latched?'门已锁定！不用清空剩余宝石，点击前进':s.op?'宝石正在下落结算，石流继续运动':s.contact?'盾前正在受压，尽快疏通底部宝石':'交换相邻宝石，让石头落入配重斗';
}
function phaseUI(){if(lastPhase===game.phase)return;lastPhase=game.phase;if(['walking','transition','won'].includes(game.phase)){toastUntil=0;$('toast').classList.remove('show');}$('overlay').classList.toggle('won',game.phase==='won');clearSelection();const visible=['ready','lost','won'].includes(game.phase);$('overlay').hidden=!visible;if(!visible)return;const b=game.active===1;if(game.phase==='ready'){$('overlay-kicker').textContent=b?'A 已完成 · B 独立挑战':'第一段旅程';$('overlay-title').textContent=b?'新的石仓，新的出口':'帮国王打开身后的门';$('overlay-copy').innerHTML=b?'生命恢复至 100 HP。<br>B 有自己的石料、配重斗和出口门。':'底口堵着，落石就会把国王推向门刺。<br>交换宝石排石，用石头的重量吊门。';$('begin').textContent=b?'开始 B 关':'开始 A 关';}else if(game.phase==='lost'){$('overlay-kicker').textContent='救援尚未成功';$('overlay-title').textContent='国王没能撑住';$('overlay-copy').textContent=b?'A 的完成状态保留。重试 B，换个消除顺序。':'先寻找能打通底口的三消组合，再救一次。';$('begin').textContent='重试当前段';}else{$('overlay-kicker').textContent='A → B · 连续旅程完成';$('overlay-title').textContent='两道门，都打开了';$('overlay-copy').textContent='国王已穿过两段独立机关，安全抵达 P2。';$('begin').textContent='从 A 再来一次';}}
function pick(event){const r=canvas.getBoundingClientRect(),x=(event.clientX-r.left)/r.width*720+game.cameraX-game.active*LinkedKing.SPAN,y=(event.clientY-r.top)/r.height*LinkedKing.HEIGHT+game.cameraY,c=Math.floor((x-LinkedKing.BX)/LinkedKing.CELL),row=Math.floor((y-LinkedKing.BY)/LinkedKing.CELL);return c>=0&&c<4&&row>=0&&row<4?row*4+c:-1;}
function choose(i){if(game.phase!=='playing'||game.paused)return;if(game.stages[game.active].op){toast('等待宝石落稳');return;}if(i<0||game.stages[game.active].board[i]==null){clearSelection();return;}if(selected<0){selected=i;renderer.selected=i;return;}if(selected===i){clearSelection();return;}const adjacent=Math.abs(selected%4-i%4)+Math.abs((selected>>2)-(i>>2))===1;if(!adjacent){selected=i;renderer.selected=i;return;}game.swap(selected,i);clearSelection();}
canvas.addEventListener('pointerdown',e=>{e.preventDefault();down=pick(e);canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointerup',e=>{e.preventDefault();const end=pick(e);if(down>=0&&end!==down&&end>=0){selected=down;choose(end);}else choose(end);down=-1;});canvas.addEventListener('pointercancel',()=>{down=-1;});
canvas.addEventListener('keydown',e=>{if(e.key==='Escape'){clearSelection();return;}if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();const step={ArrowLeft:-1,ArrowRight:1,ArrowUp:-4,ArrowDown:4}[e.key];renderer.keyboard=Math.max(0,Math.min(15,(renderer.keyboard??0)+step));renderer.hints=[renderer.keyboard];renderer.hintUntil=visualTime+20;}if(e.key==='Enter'||e.key===' '){e.preventDefault();choose(renderer.keyboard??0);}});
$('begin').onclick=()=>{if(game.phase==='won'){game.stages=[new LinkedKing.Stage(0),new LinkedKing.Stage(1)];game.active=0;game.restart();}else if(game.phase==='lost')game.restart();else game.start();phaseUI();hud();};
$('advance').onclick=()=>{game.advance();phaseUI();hud();};$('pause').onclick=()=>{game.paused=!game.paused;hud();};$('restart').onclick=()=>{game.restart();lastPhase='';phaseUI();hud();};$('hint').onclick=()=>{const h=game.stages[game.active].hint();if(h.length){renderer.hints=h;renderer.hintUntil=visualTime+5;toast('交换发光的两颗宝石');}else toast('目前没有合法三消，可尝试重排');};$('remix').onclick=()=>{toast(game.stages[game.active].remix()?'颜色已重排，石头与空位保留':'未找到合适重排，次数保留');clearSelection();hud();};
$('help').onclick=()=>{helpPaused=game.paused;game.paused=true;$('rules').showModal();hud();};$('close-help').onclick=()=>$('rules').close();$('rules').addEventListener('close',()=>{game.paused=helpPaused;hud();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&['playing','walking','transition'].includes(game.phase))game.paused=true;previous=0;});window.addEventListener('resize',()=>renderer.resize());
function frame(ms){uiTime=ms/1000;const delta=previous?Math.min(.08,(ms-previous)/1000):0;if(!game.paused&&!['ready','lost','won'].includes(game.phase))visualTime+=delta;game.update(delta);previous=ms;for(const ev of game.stages[game.active].events.splice(0)){if(ev.type==='hurt')toast('碰到门刺 −12 HP');else if(ev.type==='open')toast('门已吊起并锁定，可以前进！');else if(ev.type==='invalid')toast('需要交换出横向或竖向三连');}if(uiTime>toastUntil)$('toast').classList.remove('show');renderer.draw(game,visualTime);phaseUI();hud();requestAnimationFrame(frame);}
window.kingJourney=Object.freeze({snapshot:()=>({...game.snapshot(),selected,geometry:{cell:LinkedKing.CELL,boardX:LinkedKing.BX,boardY:LinkedKing.BY,width:720,height:LinkedKing.HEIGHT},particles:game.stages[game.active].particles.map(p=>({id:p.id,x:p.x,y:p.y,r:p.r,captured:p.captured}))})});phaseUI();hud();requestAnimationFrame(frame);
})();
