(function(root,factory){const C=factory();if(typeof module==='object')module.exports=C;else root.SandCrew=C;})(globalThis,()=>{
  const GAP=104;
  class Crew{
    constructor(world){this.w=world;const count=world.level.mechanics.crewCount??(world.level.mechanics.porter?1:0),indices=world.jars.map((_,i)=>i);for(let i=indices.length-1;i>0;i--){const j=Math.floor(world.random()*(i+1));[indices[i],indices[j]]=[indices[j],indices[i]];}world.porters=indices.slice(0,count).map(jar=>({jar,phase:'grip',elapsed:0,duration:.5,moving:false,direction:world.random()<.5?-1:1,target:world.jars[jar].x}));this.order=world.jars.map((_,i)=>i).sort((a,b)=>world.jars[a].x-world.jars[b].x);}
    bounds(p){const w=this.w,j=w.jars[p.jar],reach=w.jars.length>=4?24:w.jars.length===3?38:w.level.id<=5?36:w.level.id<=8?50:65;let left=Math.max(96,j.homeX-reach),right=Math.min(496,j.homeX+reach);
      for(const r of w.rocks)if(!r.broken&&r.y+r.ry>584&&r.y-r.ry<655){if(r.x<j.x)left=Math.max(left,r.x+r.rx+51);else right=Math.min(right,r.x-r.rx-51);}return{left,right};}
    capacity(index,dir,source){const w=this.w,j=w.jars[index];if(!j.intact)return 0;const driver=this.drives?.get(index)||w.porters.find(p=>p.jar===index);if(index!==source&&driver?.moving&&driver.direction!==dir)return 0;const limits=this.bounds({jar:index});let room=Math.max(0,dir>0?limits.right-j.x:j.x-limits.left),at=this.order.indexOf(index),next=this.order[at+dir];if(next!==undefined){const gap=Math.max(0,(w.jars[next].x-j.x)*dir-GAP);room=Math.min(room,gap+this.capacity(next,dir,source));}return room;}
    push(index,amount,dir,source){if(amount<=0)return;const w=this.w,j=w.jars[index],at=this.order.indexOf(index),next=this.order[at+dir];if(next!==undefined){const other=w.jars[next],gap=Math.max(0,(other.x-j.x)*dir-GAP),transfer=Math.max(0,amount-gap);if(transfer>0){this.push(next,transfer,dir,source);if(!j.bumpTime&&!other.bumpTime)w.events.push({type:'cart-bump',x:(j.x+other.x)/2,y:621});j.bumpTime=other.bumpTime=.2;other.pushed=true;}}j.x+=dir*amount;}
    step(dt){const w=this.w;this.drives=new Map(w.porters.map(p=>[p.jar,{moving:p.moving,direction:p.direction}]));for(const j of w.jars){j.bumpTime=Math.max(0,(j.bumpTime||0)-dt);j.pushed=false;}for(const p of w.porters){const j=w.jars[p.jar];p.elapsed+=dt;if(!j.intact){p.phase='leave';p.leaveAge=(p.leaveAge||0)+dt;p.moving=false;continue;}const {left,right}=this.bounds(p);
        if(p.moving){const from=j.x,speed=34+28*Math.sin(Math.min(1,p.elapsed/p.duration)*Math.PI),at=this.order.indexOf(p.jar),next=this.order[at+p.direction],touch=next!==undefined&&Math.abs(w.jars[next].x-j.x)<=GAP+2,step=Math.min(speed*dt/(touch?1.45:1),this.capacity(p.jar,p.direction,p.jar));this.push(p.jar,step,p.direction,p.jar);
          if(Math.abs(j.x-from)<.001||p.elapsed>=p.duration||(p.direction>0?j.x>=p.target:j.x<=p.target)){p.moving=false;p.elapsed=0;p.duration=.55+w.random()*1.1;p.phase=['rest','wipe','think'][Math.floor(w.random()*3)];if(Math.abs(j.x-from)<.001)p.direction=-p.direction;w.events.push({type:'rest'});}
        }else if(p.elapsed>=p.duration){p.direction=w.random()<.3?-p.direction:p.direction;if(j.x<=left+2)p.direction=1;if(j.x>=right-2)p.direction=-1;p.target=Math.max(left,Math.min(right,j.x+p.direction*(15+w.random()*65)));p.duration=.65+w.random()*.8;p.elapsed=0;p.moving=true;p.phase=p.direction>0?'walk':'return';w.effects.porterTrips++;w.events.push({type:'shuffle'});}
      }}
  }return Crew;
});
