async (page) => {
  const solutions=/* SOLUTIONS */ null;await page.reload();await page.setViewportSize({width:1280,height:800});
  const drag=async(points)=>{const b=await page.locator('#game').boundingBox();await page.mouse.move(b.x+points[0][0]*b.width/560,b.y+points[0][1]*b.height/760);await page.mouse.down();for(const p of points.slice(1))await page.mouse.move(b.x+p[0]*b.width/560,b.y+p[1]*b.height/760,{steps:15});await page.mouse.up();};
  const win=async()=>{for(const route of solutions[0])await drag([...route].reverse());await page.waitForFunction(()=>sandGame.snapshot().state==='won',null,{timeout:20000});return page.evaluate(()=>sandGame.snapshot());};
  await drag([[60,350],[60,450]]);const first=await win();await page.getByRole('button',{name:'再玩一次，挑战更少挖沙',exact:true}).click();const better=await win();if(better.dug>=first.dug||!await page.locator('#result-record').textContent().then(t=>t.includes('新纪录')))throw Error('Improvement not recorded');
  await page.getByRole('button',{name:'再玩一次，挑战更少挖沙',exact:true}).click();await drag([[60,350],[60,450]]);const worse=await win();if(worse.bestSand[0][1]!==better.dug)throw Error('Worse result replaced record');
  await page.getByRole('button',{name:'再玩一次，挑战更少挖沙',exact:true}).click();await drag([[50,575],[50,340],[135,210],[135,164],[135,130]]);await page.waitForFunction(()=>sandGame.snapshot().state==='lost',null,{timeout:15000});await page.getByRole('button',{name:'查看失误位置',exact:true}).click();
  const frozen=await page.evaluate(()=>sandGame.snapshot());if(!frozen.failure||frozen.stars!==0||frozen.bestSand[0][1]!==better.dug||await page.locator('#result').isVisible())throw Error('Failure review invalid');await page.waitForTimeout(1200);const after=await page.evaluate(()=>sandGame.snapshot());if(JSON.stringify(frozen)!==JSON.stringify(after))throw Error('Review advances physics');await page.screenshot({path:'output/playwright/failure-review.png'});
  await page.getByRole('button',{name:'重来',exact:true}).click();await drag([[50,300],[50,302]]);await page.waitForFunction(()=>document.querySelector('#board-instruction').textContent.includes('停在沙中'),null,{timeout:12000});
  await page.reload();const reset=await page.evaluate(()=>sandGame.snapshot());if(reset.bestSand.length||reset.best.length||reset.dug||reset.level!==1)throw Error('Refresh retained records');await page.evaluate(r=>window.__reviewChecks=r,{first:first.dug,better:better.dug,worse:worse.dug,reviewFrozen:true,failureNoRecord:true,idleState:true,refreshReset:true});
}
