async page=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.reload();await page.waitForFunction(()=>window.sandGame?.snapshot().assetsReady);
 const select=async n=>{await page.getByRole('button',{name:'选择关卡'}).click();await page.locator(`[data-level="${n-1}"]`).click();await page.locator('#game').scrollIntoViewIfNeeded();};
 await select(2);const start=await page.evaluate(()=>sandGame.snapshot());await page.waitForTimeout(600);const automatic=await page.evaluate(()=>sandGame.snapshot());if(automatic.time<=start.time||automatic.dug||automatic.rival.removed<=start.rival.removed)throw Error('Opponent failed to start without digging');
 await page.getByRole('button',{name:'开启音效',exact:true}).click();await page.waitForFunction(()=>sandGame.snapshot().rival.removed>20);
 await page.getByRole('button',{name:'玩法说明 ?'}).click();const before=await page.evaluate(()=>sandGame.snapshot());await page.waitForTimeout(700);if(JSON.stringify(before)!==JSON.stringify(await page.evaluate(()=>sandGame.snapshot())))throw Error('Rules failed to pause rival');await page.getByRole('button',{name:'关闭玩法说明'}).click();
 await page.waitForFunction(()=>sandGame.snapshot().rival.danger==='near'||sandGame.snapshot().state==='lost',null,{timeout:50000});await page.locator('#game').screenshot({path:'output/playwright/rival-near.png'});
 await page.waitForFunction(()=>sandGame.snapshot().state==='lost',null,{timeout:15000});const lost=await page.evaluate(()=>sandGame.snapshot());if(lost.failure.kind!=='stolen'||lost.stars!==0||lost.collected!==0||lost.rival.removed<=0)throw Error(JSON.stringify(lost));if(await page.locator('#result-stars').isVisible())throw Error('Stolen bead awarded stars');await page.screenshot({path:'output/playwright/rival-stolen.png',fullPage:true});
 await page.getByRole('button',{name:'查看失误位置',exact:true}).click();await page.waitForTimeout(500);if(JSON.stringify(lost)!==JSON.stringify(await page.evaluate(()=>sandGame.snapshot())))throw Error('Failure not frozen');await page.getByRole('button',{name:'重来',exact:true}).click();const retry=await page.evaluate(()=>sandGame.snapshot());if(retry.dug||retry.failure||retry.time>1)throw Error('Rival did not reset');
 await page.getByRole('button',{name:'关闭音效',exact:true}).click();const muted=await page.evaluate(()=>sandGame.snapshot().audioPlayed);
 await page.setViewportSize({width:390,height:844});await select(2);const cdp=await page.context().newCDPSession(page),b=await page.locator('#game').boundingBox(),point=p=>({x:b.x+p[0]*b.width/560,y:b.y+p[1]*b.height/760});
 const routes=[[[235,330],[235,364],[165,435],[130,575]],[[120,110],[120,144],[235,200],[395,300],[425,420],[425,575]]];
 for(const r of routes){const points=r.slice().reverse();await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[point(points[0])]});for(let i=1;i<points.length;i++){const a=points[i-1],z=points[i];for(let k=1;k<=12;k++)await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[point([a[0]+(z[0]-a[0])*k/12,a[1]+(z[1]-a[1])*k/12])]});}await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});}
 await page.waitForFunction(()=>sandGame.snapshot().state!=='playing',null,{timeout:22000});const won=await page.evaluate(()=>sandGame.snapshot());if(won.state!=='won'||won.stars!==3||won.collected!==11||won.rival.captured)throw Error(JSON.stringify(won));if(won.audioPlayed!==muted)throw Error('Muted sounds played');await page.waitForFunction(()=>getComputedStyle(document.querySelector('.result-card')).opacity==='1');await page.screenshot({path:'output/playwright/rival-mobile-win.png',fullPage:true});
 if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Mobile overflow');if(await page.locator('#hint').count())throw Error('Hints returned');
 await page.reload();await page.waitForFunction(()=>sandGame.snapshot().assetsReady);const fresh=await page.evaluate(()=>({s:sandGame.snapshot(),storage:localStorage.length+sessionStorage.length}));if(fresh.s.level!==1||fresh.s.best.length||fresh.s.rival||fresh.s.soundEnabled||fresh.storage)throw Error('Refresh/storage contract changed');
 if(errors.length)throw Error(errors.join(';'));return await page.evaluate(r=>window.__rivalChecks=r,{automaticStart:true,theft:{time:lost.time,kind:lost.failure.kind,stars:lost.stars,excavated:lost.rival.removed},touchWin:{stars:won.stars,collected:won.collected,rivalMoved:won.rival.removed>0},pause:true,freeze:true,restart:true,sound:true,refresh:true,noStorage:true,errors});
}
