const{test}=require('node:test'),assert=require('node:assert/strict');const{World}=require('../core.js');
const base=extra=>({jars:[{x:280,color:'blue'}],groups:[{x:80,y:100,color:'blue',count:3}],rocks:[],tunnels:[],mechanics:{},budget:{three:1000,two:2000},targetScore:10,...extra});
test('rock support loss warns immediately and falls only after .55s, with old mask removed',()=>{const w=new World(base({rocks:[{x:280,y:250,rx:20,ry:18}]}));for(let i=0;i<60;i++)w.step();assert.equal(w.rocks[0].y,250);w.terrain.line([240,280],[320,280],22,'player');w.step();assert.equal(w.rocks[0].phase,'warning');for(let i=0;i<50;i++)w.step();assert.equal(w.rocks[0].y,250);for(let i=0;i<70;i++)w.step();assert.ok(w.rocks[0].y>250);assert.equal(w.terrain.rockMask[120*280+140],0);});
test('falling rock breaks a cart and kills a worm exactly once',()=>{const w=new World(base({rocks:[{x:280,y:530,rx:20,ry:20}],mechanics:{worms:[{x:280,y:550,speed:0,range:1,depth:1}]}}));w.terrain.line([280,548],[280,580],40);for(let i=0;i<240&&w.state==='playing';i++)w.step();assert.equal(w.jars[0].intact,false);assert.equal(w.worms[0].alive,false);assert.equal(w.events.filter(e=>e.type==='cart-broken').length,1);});
test('swept bead contact opens treasure once and does not consume the bead',()=>{const w=new World(base({treasures:[{x:200,y:300,points:20}]}));const b=w.balls[0];Object.assign(b,{previousX:200,previousY:270,x:200,y:330});w.hazards.touchBead(b);w.hazards.touchBead(b);w.resolveInteractions();assert.equal(w.score,20);assert.equal(w.treasures[0].opened,true);assert.equal(b.active,true);});
test('bead ignites fuse, three seconds to blast, terrain change is free and only once',()=>{const w=new World(base({rocks:[{x:280,y:300,rx:30,ry:25}],bombs:[{pad:{x:150,y:400},rock:0}]})),b=w.balls[0];Object.assign(b,{previousX:150,previousY:380,x:150,y:420});w.hazards.touchBead(b);w.resolveInteractions();assert.equal(w.bombs[0].state,'burning');const cost=w.terrain.units;for(let i=0;i<300;i++)w.step();assert.equal(w.bombs[0].state,'burning');for(let i=0;i<100;i++)w.step();assert.equal(w.bombs[0].state,'spent');assert.equal(w.rocks[0].broken,true);assert.equal(w.terrain.units,cost);assert.equal(w.events.filter(e=>e.type==='blast').length,1);});
test('supported rocks never penetrate an intact thin horizontal sand floor',()=>{const w=new World(base({rocks:[{x:280,y:240,rx:18,ry:18}]}));w.terrain.line([240,265],[320,265],20);for(let i=0;i<600;i++)w.step();assert.ok(w.rocks[0].y+w.rocks[0].ry<289);});
test('blast radius tests the visible ellipse, not its oversized bounding circle',()=>{const w=new World(base({rocks:[{x:200,y:300,rx:20,ry:20},{x:209,y:410,rx:70,ry:10}],bombs:[{pad:{x:80,y:400},rock:0}]}));w.bombs[0].state='burning';w.hazards.explode(w.bombs[0]);assert.equal(w.rocks[0].broken,true);assert.equal(w.rocks[1].broken,false);});

test('falling rock stuns thief and stops digging and theft for the stun period',()=>{const w=new World(base({rocks:[{x:280,y:300,rx:25,ry:22}],mechanics:{rival:{speed:0}}}));Object.assign(w.rival,{x:280,y:365});w.terrain.line([280,325],[280,425],50,'player');for(let i=0;i<300&&!w.rival.stunTime;i++)w.step();assert.ok(w.rival.stunTime>3.9);const dug=w.rival.removed,stolen=w.losses.stolen;for(let i=0;i<120;i++)w.step();assert.equal(w.rival.removed,dug);assert.equal(w.losses.stolen,stolen);assert.ok(w.rival.stunTime>2.9);});
