const {test}=require('node:test'),assert=require('node:assert/strict'),{World,jarMouth}=require('../core.js');
const level={jars:[{x:180,color:'amber'},{x:430,color:'blue'}],groups:[{x:180,y:120,color:'amber',count:1}],rocks:[],tunnels:[],budget:{three:100,two:200},mechanics:{porter:true}};
function away(){const w=new World(level,{seed:1});for(let i=0;i<7200;i++){w.crew.step(1/120);const j=w.jars[w.porter.jar];if(Math.abs(j.x-j.homeX)>53){w.balls[0].color=j.color;return w;}}throw Error('cart never reached an off-home position');}
function drop(w,x,y){Object.assign(w.balls[0],{x,y,vy:200,vx:0});for(let i=0;i<80&&w.state==='playing';i++)w.step();return w;}
test('actual moving cart receives beads without a fixed tray or waiting queue',()=>{const w=away(),j=w.jars[w.porter.jar];drop(w,j.x,jarMouth(j).y-12);assert.equal(w.state,'won');assert.equal(j.balls.length,1);assert.equal('waiting'in j,false);});
test('old home position misses when real opening has moved away',()=>{const w=away(),j=w.jars[w.porter.jar];drop(w,j.homeX,jarMouth(j).y-12);assert.equal(w.state,'lost');assert.equal(w.failure.kind,'missed');});
test('collection follows motion on fixed rails for all bead materials',()=>{for(const type of ['glass','heavy','rubber','light']){const w=new World({...level,groups:[{...level.groups[0],type}]},{seed:1});for(let i=0;i<720&&!w.porter.moving;i++)w.step();const j=w.jars[w.porter.jar],start=j.x;w.balls[0].color=j.color;drop(w,j.x,jarMouth(j).y-5);assert.equal(w.state,'won',type);assert.notEqual(j.x,start);}});
test('bead already below the mouth cannot be vacuumed through the side',()=>{const w=away(),j=w.jars[w.porter.jar];drop(w,j.x,jarMouth(j).y+12);assert.equal(w.state,'lost');});
test('unreachable wrong-color result freezes at actual contact position',()=>{const w=away(),j=w.jars[w.porter.jar];w.balls[0].color=j.color==='blue'?'amber':'blue';drop(w,j.x,jarMouth(j).y-10);assert.equal(w.failure.kind,'wrong-color');assert.equal(w.failure.targetX,j.x);const frozen=w.snapshot();for(let i=0;i<50;i++)w.step();assert.deepEqual(w.snapshot(),frozen);});
test('panic brake has no drift and assignments never teleport between carts',()=>{const w=away(),j=w.jars[w.porter.jar],x=j.x,assigned=w.porter.jar;w.random=()=>.9;w.crew.scare();for(let i=0;i<35;i++)w.crew.step(1/120);assert.equal(j.x,x);for(let i=0;i<7200;i++){const previous=w.jars.map(j=>j.x);w.crew.step(1/120);assert.ok(w.jars.every((j,k)=>Math.abs(j.x-previous[k])<=48/120+1e-6));}assert.equal(w.porter.jar,assigned);});
test('random assignment covers every cart',()=>{const picked=new Set();for(let seed=0;seed<20;seed++)picked.add(new World(level,{seed:seed*98765}).porter.jar);assert.equal(picked.size,2);});
