const {test}=require('node:test');const assert=require('node:assert/strict');const {World,jarMouth}=require('../core.js');
const level={jars:[{x:180,color:'amber'},{x:430,color:'blue'}],groups:[{x:180,y:120,color:'amber',count:1}],rocks:[],tunnels:[],budget:{three:100,two:200},mechanics:{porter:true}};
function away(){const w=new World(level,{seed:1});w.started=true;while(w.porter.phaseIndex!==4)w.step();return w;}
function drop(w,x,y){const b=w.balls[0];Object.assign(b,{x,y,vy:200,vx:0});for(let i=0;i<80&&w.state==='playing';i++)w.step();return w;}
test('actual moving jar receives beads, with no fixed receiving tray or pending queue',()=>{const w=away(),j=w.jars[w.porter.jar];assert.ok(Math.abs(j.x-j.homeX)>60);drop(w,j.x,jarMouth(j).y-12);assert.equal(w.state,'won');assert.equal(w.collected,1);assert.equal(j.balls.length,1);assert.equal(w.stars,3);assert.equal('waiting' in j,false);assert.equal('transfers' in w.snapshot(),false);});
test('old home position misses while the real jar is away',()=>{const w=away(),j=w.jars[w.porter.jar];drop(w,j.homeX,jarMouth(j).y-12);assert.equal(w.state,'lost');assert.equal(w.failure.kind,'missed');assert.equal(w.collected,0);assert.equal(w.stars,0);});
test('collection follows horizontal motion and lift for all bead materials',()=>{for(const type of ['glass','heavy','rubber','light']){const w=new World({...level,groups:[{...level.groups[0],type}]},{seed:1});w.started=true;while(w.porter.phase!=='walk')w.step();for(let i=0;i<65;i++)w.step();const j=w.jars[w.porter.jar],start=j.x;drop(w,j.x,jarMouth(j).y-5);assert.equal(w.state,'won',type);assert.notEqual(j.x,start);}});
test('a bead already below the mouth cannot be vacuumed into the side of a jar',()=>{const w=away(),j=w.jars[0];drop(w,j.x,jarMouth(j).y+12);assert.equal(w.state,'lost');assert.equal(w.collected,0);});
test('wrong-color failure highlights the actual displaced jar and freezes physics',()=>{const w=away(),j=w.jars[0];w.balls[0].color='blue';drop(w,j.x,jarMouth(j).y-10);assert.equal(w.failure.kind,'wrong-color');assert.equal(w.failure.targetX,j.x);assert.equal(w.failure.targetY,jarMouth(j).y);assert.notEqual(w.failure.targetX,j.homeX);assert.equal(w.stars,0);const frozen=w.snapshot();for(let i=0;i<50;i++)w.step();assert.deepEqual(w.snapshot(),frozen);});
test('porter rests, stays on screen and returns every trip without repeating jars',()=>{const w=new World(level,{seed:1});w.started=true;const visited=new Set();let moving=false,returned=false;for(let i=0;i<1900;i++){w.step();const p=w.porter,j=w.jars[p.jar];visited.add(p.phase);assert.ok(j.x>=56&&j.x<=504);if(Math.abs(j.x-j.homeX)>20)moving=true;if(moving&&p.phase==='home')returned=true;}assert.ok(visited.has('rest'));assert.ok(visited.has('walk'));assert.ok(returned);assert.ok(w.effects.porterTrips>=2);});
test('porter rests without drifting',()=>{const w=away(),j=w.jars[w.porter.jar],x=j.x;for(let i=0;i<50;i++)w.step();assert.equal(j.x,x);assert.equal(w.porter.moving,false);});
test('seeded random choice covers every jar without repeating the previous one',()=>{const picked=new Set();for(let seed=0;seed<20;seed++){const w=new World(level,{seed:seed*98765});picked.add(w.porter.jar);const first=w.porter.jar;w.choosePorter();assert.notEqual(w.porter.jar,first);}assert.equal(picked.size,2);});
test('regression seeds exercise every initial jar, including four-color stages',()=>{const levels=require('../levels.js');for(const l of levels.filter(l=>l.mechanics.porter)){const choices=new Set([1,300,1000,100000].map(seed=>new World(l,{seed}).porter.jar));assert.equal(choices.size,l.jars.length);}});
