const {test}=require('node:test'),a=require('node:assert/strict'),{World}=require('../core.js'),levels=require('../levels.js');
function make(){return new World({id:12,timeLimit:90,jars:[{x:150,color:'amber'},{x:254,color:'blue'},{x:370,color:'jade'}],groups:[{x:260,y:150,count:18,color:'amber'}],rocks:[],tunnels:[],mechanics:{rival:{speed:30},crewCount:1},budget:{three:1000,two:2000},targetScore:10},{seed:7});}
function tick(w,n){for(let i=0;i<n;i++){w.rival.step(w,1/120);w.resolveInteractions();}}
function near(w){const r=w.rival,b=w.balls[0],A=require('../rival-animation.js');Object.assign(b,A.point(r,A.pickup[2]),{vx:0,vy:0});return b;}
test('theft reaches, physically lifts, then stows one real bead; no instant vacuum',()=>{const w=make(),b=near(w),r=w.rival;tick(w,1);a.equal(w.losses.stolen,0);a.equal(r.phase,'reach');tick(w,38);a.ok(b.held);a.equal(b.active,true);a.equal(w.losses.stolen,0);const hand=r.heldPoint();a.ok(Math.hypot(b.x-hand.x,b.y-hand.y)<1);tick(w,120);a.equal(w.losses.stolen,1);a.equal(b.active,false);a.equal(r.bag[0],b);a.equal(r.bag.length,1);});
test('a moving bead escapes an outstretched hand and stunning releases a held bead',()=>{const w=make(),b=near(w),r=w.rival;tick(w,1);b.x+=100;tick(w,40);a.equal(w.losses.stolen,0);a.equal(b.held,undefined);Object.assign(b,require('../rival-animation.js').point(r,require('../rival-animation.js').pickup[2]));tick(w,45);a.ok(b.held);r.stun(w,1);a.equal(b.held,false);a.equal(b.active,true);a.equal(w.losses.stolen,0);a.ok(b.theftImmuneUntil>w.time);});
test('bag load enlarges visible sack and increases stamina cost',()=>{const empty=make(),heavy=make();heavy.rival.bag=heavy.balls.splice(2,8);for(const w of [empty,heavy]){w.rival.hearingCooldown=100;tick(w,120);}a.ok(heavy.rival.stamina<empty.rival.stamina-2);a.ok(heavy.rival.bagScale>empty.rival.bagScale);});
test('overloaded sack tear uses moving seconds, not frames or standing time; spills same bead',()=>{const w=make(),r=w.rival;r.bag=w.balls.slice(2,10);for(const b of r.bag){b.active=false;b.stolen=true;}w.losses.stolen=8;let rolls=0;w.random=()=>{rolls++;return .049;};r.moveBag(w,10,0);a.equal(rolls,0);r.moveBag(w,.99,20);a.equal(rolls,0);r.moveBag(w,.01,.2);a.equal(rolls,1);a.equal(r.torn,true);const old=new Set(r.bag);r.moveBag(w,.8,15);const dropped=[...old].filter(b=>b.active);a.ok(dropped.length>=1);a.equal(w.balls.length,18);a.equal(w.losses.stolen,8-dropped.length);a.equal(w.score,0);for(const b of dropped){w.receive(w.jars[0],b);w.receive(w.jars[0],b);}a.equal(w.score,dropped.length*10);});
test('six jewels cannot tear a bag; 5 percent boundary rejects .05',()=>{for(const n of [6,7]){const w=make(),r=w.rival;r.bag=w.balls.slice(0,n);w.random=()=>.05;r.moveBag(w,1,20);a.equal(r.torn,false);}});
test('one driven cart pushes a passive cart and transmits contact through a chain',()=>{const w=make();w.porters=[{jar:0,moving:true,direction:1,elapsed:0,duration:10,target:220,phase:'walk'}];const before=w.jars.map(j=>j.x);w.operator.activeJar=0;for(let i=0;i<120;i++)w.crew.step(1/120);a.ok(w.jars[1].x>before[1]+5);a.ok(w.jars[2].x>before[2]);a.ok(w.jars.every((j,i)=>!i||j.x-w.jars[i-1].x>=104-1e-6));a.ok(w.events.some(e=>e.type==='cart-bump'));});
test('pushing a blocked chain does not move wrecks, exchange order or teleport',()=>{const w=make();w.jars[1].intact=false;w.porters=[{jar:0,moving:true,direction:1,elapsed:0,duration:10,target:220,phase:'walk'}];w.operator.activeJar=0;for(let i=0;i<120;i++){const x=w.jars[0].x;w.crew.step(1/120);a.ok(Math.abs(w.jars[0].x-x)<=48/120+1e-6);a.ok(w.jars[0].x<=150+1e-6);}a.equal(w.jars[1].x,254);});
test('bomb triggers sit upstream of their useful rock obstacle in every shipped level',()=>{for(const l of levels)for(const b of l.bombs){const r=l.rocks[b.rock];a.ok(b.pad.y<r.y-r.ry-20,`level ${l.id} upstream trigger`);a.ok(b.fuseSeconds>=1&&b.fuseSeconds<=3);}});
test('score potential includes a small bag that can still be overloaded, but not an unfillable bag',()=>{const w=new World(levels[1],{seed:1});for(const b of w.balls.slice(0,4)){w.rival.bag.push(b);w.resolveBead(b,'stolen');w.checkOutcome();}a.equal(w.state,'playing');a.equal(w.remainingPotential(),110);for(const b of w.balls.slice(4,10))w.resolveBead(b,'missed');a.equal(w.remainingPotential(),10);w.checkOutcome();a.equal(w.state,'lost');});
test('an existing rock blocks the complete lifting path without carrying a bead through it',()=>{const l={id:2,jars:[{x:280,color:'amber'}],groups:[{x:80,y:100,count:3,color:'amber'}],rocks:[{x:280,y:350,rx:60,ry:30}],tunnels:[],mechanics:{rival:{speed:0}},budget:{three:1000,two:2000},targetScore:10},w=new World(l),r=w.rival,b=w.balls[0];Object.assign(r,{x:280,y:398});Object.assign(b,{x:290,y:398,vx:0,vy:0});w.terrain.dig(280,399,16,'initial');let released=false;for(let i=0;i<150;i++){w.step();if(b.theftImmuneUntil)released=true;const rock=w.rocks[0];a.ok(((b.x-rock.x)/(rock.rx+b.r))**2+((b.y-rock.y)/(rock.ry+b.r))**2>=.98);}a.equal(w.losses.stolen,0);a.equal(!!b.held,false); /* Complete hand path is rejected before lifting through an existing rock. */});
test('a bead at the painted inner edge is caught by the actual pushed empty cart',()=>{for(const edge of [-45.8,45.8]){const w=make();w.porters=[{jar:0,moving:true,direction:1,elapsed:0,duration:10,target:220,phase:'walk'}];const b=w.balls[0];Object.assign(b,{color:'blue',x:254+edge,y:589,vx:0,vy:240});w.step();a.equal(w.score,10);a.ok(w.catches[0].mouthX>254);a.ok(Math.abs(w.catches[0].offset)<=46);}});
test('only selected motor is powered even if stale opposite intents exist',()=>{const w=make();w.porters=[{jar:0,moving:true,direction:1,elapsed:0,velocity:0},{jar:1,moving:true,direction:-1,elapsed:0,velocity:0}];w.operator.activeJar=0;for(let i=0;i<50;i++){w.crew.step(1/120);a.ok(w.jars[1].x-w.jars[0].x>=104-1e-6);a.ok(w.porters.filter(p=>p.moving).length<=1);a.equal(w.operator.signalColor,'amber');}});
