const {test}=require('node:test'),assert=require('node:assert/strict');const {World}=require('../core.js'),levels=require('../levels.js');
test('rival starts on level 2, is visible but cannot steal before the first dig',()=>{assert.equal(new World(levels[0]).rival,null);for(const l of levels.slice(1)){const w=new World(l),at=w.rival.snapshot();for(let i=0;i<600;i++)w.step();assert.deepEqual(w.rival.snapshot(),at);assert.equal(w.state,'playing');}});
test('visible rival excavates real terrain without charging the player and eventually steals',()=>{const w=new World(levels[1]);w.dig([280,70],[280,70],14);const cost=w.terrain.units,start={x:w.rival.x,y:w.rival.y};let actual=0;for(let i=0;i<9000&&w.state==='playing';i++){const before={x:w.rival.x,y:w.rival.y};w.step();assert.ok(Math.hypot(w.rival.x-before.x,w.rival.y-before.y)<1);actual=Math.max(actual,w.rival.removed);}assert.equal(w.state,'lost');assert.equal(w.failure.kind,'stolen');assert.ok(actual>100);assert.ok(Math.hypot(w.rival.x-start.x,w.rival.y-start.y)>50);assert.equal(w.terrain.units,cost);assert.equal(w.collected,0);assert.equal(w.stars,0);assert.equal(w.balls.filter(b=>b.stolen).length,1);const frozen=w.snapshot();for(let i=0;i<100;i++)w.step();assert.deepEqual(w.snapshot(),frozen);});
test('theft requires actual contact, never an elapsed-time deadline',()=>{const w=new World(levels[1]);w.started=true;w.rival.speed=0;for(let i=0;i<15000;i++)w.step();assert.equal(w.state,'playing');assert.equal(w.collected,0);assert.equal(w.stars,0);});
test('pursuer routes around stone and keeps its body on the board',()=>{const w=new World(levels[10]);w.started=true;let walked=0;for(let i=0;i<7200&&w.state==='playing';i++){w.step();assert.ok(w.rival.clear(w.rival.x,w.rival.y));assert.ok(w.rival.x>=42&&w.rival.x<=518);walked+=1;}assert.ok(walked>120);assert.ok(w.rival.removed>0);});
test('a delivered bead can never be stolen and completion wins immediately',()=>{const w=new World(levels[1]);for(const b of w.balls)w.receive(w.jars.find(j=>j.color===b.color),b);w.started=true;w.step();assert.equal(w.state,'won');assert.equal(w.rival.captured,null);assert.equal(w.collected,w.total);});
test('rival retargets remaining beads after its target is delivered',()=>{const w=new World(levels[1]);w.started=true;for(let i=0;i<240;i++)w.step();const target=w.rival.target;assert.ok(target);w.receive(w.jars.find(j=>j.color===target.color),target);w.step();assert.notEqual(w.rival.target,target);assert.ok(w.rival.target.active);});
test('porter covers the first walking segment in half the old time and still rests',()=>{const w=new World(levels[2],{seed:1});w.started=true;for(let i=0;i<132;i++)w.step();assert.ok(Math.abs(w.jars[0].x-w.jars[0].homeX)>45);assert.ok(['walk','rest'].includes(w.porter.phase));});

test('edge beads do not permanently distract the pursuer from reachable treasure',()=>{const Rival=require('../rival.js'),balls=[{x:9,y:232,r:8.5,vx:0,vy:0,active:true,color:'amber'},{x:100,y:270,r:8.5,vx:0,vy:0,active:true,color:'blue'}],level={rocks:[],mechanics:{rival:{speed:12}}},r=new Rival(level,balls);r.x=56;r.y=232;r.age=2;let stolen=false;const w={balls,terrain:{solid:()=>true,dig:()=>1},end:()=>{stolen=true;}};for(let i=0;i<1200&&!stolen;i++)r.step(w,1/120);assert.equal(stolen,true);});
