const{test}=require('node:test'),a=require('node:assert/strict'),{World}=require('../core.js');
const make=(extra={})=>new World({jars:[{x:280,color:'amber'}],groups:[{x:280,y:120,count:6,color:'amber'}],rocks:[],tunnels:[],mechanics:{},budget:{three:100,two:200},targetScore:40,timeLimit:1,...extra});
test('reaching the gate keeps play active, further catches produce a higher final score',()=>{const w=make();for(const b of w.balls.slice(0,4))w.resolveBead(b,'collected');w.checkOutcome();a.equal(w.score,40);a.equal(w.state,'playing');a.equal(w.stars,0);w.resolveBead(w.balls[4],'collected');w.checkOutcome();a.equal(w.state,'playing');w.resolveBead(w.balls[5],'collected');w.checkOutcome();a.equal(w.state,'won');a.equal(w.score,60);a.equal(w.endCause,'exhausted');});
test('deadline settles both pass and fail, preserving accumulated points',()=>{for(const n of [3,4,5]){const w=make();for(const b of w.balls.slice(0,n))w.resolveBead(b,'collected');for(let i=0;i<120;i++)w.step();a.equal(w.state,n>=4?'won':'lost');a.equal(w.score,n*10);a.equal(w.endCause,'timeout');a.equal(w.timeRemaining,0);a.ok(Math.abs(w.time-1)<1e-9);const frozen=w.snapshot();w.step();a.deepEqual(w.snapshot(),frozen);}});
test('too little remaining potential fails before the deadline; one lost gem does not',()=>{const w=make();w.resolveBead(w.balls[0],'stolen');w.checkOutcome();a.equal(w.state,'playing');w.resolveBead(w.balls[1],'missed');w.checkOutcome();a.equal(w.state,'playing');w.resolveBead(w.balls[2],'wrong-color');w.checkOutcome();a.equal(w.state,'lost');a.equal(w.endCause,'unreachable');a.equal(w.time,0);});
test('late losses cannot undo the passed gate, but do not stop other scoring',()=>{const w=make();for(const b of w.balls.slice(0,4))w.resolveBead(b,'collected');w.resolveBead(w.balls[4],'stolen');w.checkOutcome();a.equal(w.state,'playing');w.resolveBead(w.balls[5],'collected');w.checkOutcome();a.equal(w.state,'won');a.equal(w.score,50);});
test('a catch before the deadline counts, a bead below the deadline crossing cannot score later',()=>{for(const y of [589,580]){const w=make({timeLimit:.01,targetScore:10});Object.assign(w.balls[0],{x:280,y,vy:200});w.step(.1);a.equal(w.time,.01);a.equal(w.state,y===589?'won':'lost');a.equal(w.score,y===589?10:0);a.equal(w.endCause,'timeout');}});
test('reaching the gate does not discard later treasure or loss events in the same step',()=>{const w=make({targetScore:10});w.queueInteraction({u:.2,kind:'collect',apply:()=>w.resolveBead(w.balls[0],'collected')});w.queueInteraction({u:.6,kind:'treasure',apply:()=>w.score+=20});w.queueInteraction({u:.8,kind:'theft',apply:()=>w.resolveBead(w.balls[1],'stolen')});w.resolveInteractions();a.equal(w.state,'playing');a.equal(w.score,30);a.equal(w.losses.stolen,1);});
test('deadline waits for every contact in the final physical step before settling',()=>{const w=make({targetScore:10});w.time=1;w.queueInteraction({u:.1,kind:'collect',apply:()=>w.resolveBead(w.balls[0],'collected')});w.queueInteraction({u:.9,kind:'treasure',apply:()=>w.score+=20});w.resolveInteractions();a.equal(w.score,30);a.equal(w.state,'won');a.equal(w.endCause,'timeout');});
