const{test}=require('node:test'),assert=require('node:assert/strict');const{World}=require('../core.js');
const fixture=(n=3,targetScore=20)=>({jars:[{x:280,color:'amber'}],groups:[{x:280,y:120,count:n,color:'amber'}],rocks:[],tunnels:[],mechanics:{},budget:{three:100,two:200},targetScore});
test('one stolen/wrong/missed bead is zero points and play continues while target remains achievable',()=>{for(const why of ['stolen','wrong-color','missed']){const w=new World(fixture());w.resolveBead(w.balls[0],why);w.checkOutcome();assert.equal(w.state,'playing');w.resolveBead(w.balls[1],'collected');w.resolveBead(w.balls[2],'collected');w.checkOutcome();assert.equal(w.state,'won');assert.equal(w.score,20);assert.equal(w.stars,3);}});
test('mathematically unreachable target fails, never deducting already earned points',()=>{const w=new World(fixture(4,30));w.resolveBead(w.balls[0],'collected');w.resolveBead(w.balls[1],'stolen');w.resolveBead(w.balls[2],'missed');w.checkOutcome();assert.equal(w.score,10);assert.equal(w.remainingPotential(),10);assert.equal(w.state,'lost');assert.equal(w.stars,0);});
test('already resolved bead cannot score twice',()=>{const w=new World(fixture());w.resolveBead(w.balls[0],'collected');w.resolveBead(w.balls[0],'collected');assert.equal(w.score,10);});
test('no active bead means unopened treasure is no longer potential',()=>{const w=new World({...fixture(1,20),treasures:[{x:100,y:300,points:20}]});w.resolveBead(w.balls[0],'missed');assert.equal(w.remainingPotential(),0);w.checkOutcome();assert.equal(w.state,'lost');});
test('same-time treasure and collection resolve before damage, and victory stops later events',()=>{const w=new World(fixture(1,30));let damaged=false;w.queueInteraction({u:.4,kind:'damage',apply:()=>{damaged=true;}});w.queueInteraction({u:.4,kind:'collect',apply:()=>w.resolveBead(w.balls[0],'collected')});w.queueInteraction({u:.4,kind:'treasure',apply:()=>w.score+=20});w.queueInteraction({u:.5,kind:'loss',apply:()=>{throw Error('after victory');}});w.resolveInteractions();assert.equal(w.score,30);assert.equal(w.state,'won');assert.equal(damaged,true);});
test('different-time cart break versus catch uses contact order',()=>{for(const early of [true,false]){const w=new World(fixture(2,10));w.queueInteraction({u:early?.2:.8,kind:'damage',apply:()=>w.jars[0].intact=false});w.queueInteraction({u:.5,kind:'collect',apply:()=>w.resolveBead(w.balls[0],w.jars[0].intact?'collected':'wrong-color')});w.resolveInteractions();assert.equal(w.score,early?0:10);assert.equal(w.state,early?'lost':'playing');}});
test('stun resolves before same-time theft',()=>{const w=new World(fixture());let stunned=false;w.queueInteraction({u:.5,kind:'theft',apply:()=>{if(!stunned)w.resolveBead(w.balls[0],'stolen');}});w.queueInteraction({u:.5,kind:'damage',apply:()=>stunned=true});w.resolveInteractions();assert.equal(w.balls[0].active,true);});
