const{test}=require('node:test'),a=require('node:assert/strict'),{World}=require('../core.js'),G=require('../rock-geometry.js');
const base=extra=>({id:8,jars:[{x:280,color:'blue'}],groups:[{x:80,y:100,color:'blue',count:9}],rocks:[],tunnels:[],mechanics:{crewCount:1,rival:{speed:34}},budget:{three:3000,two:4000},targetScore:10,...extra});
function blast(w,roll){w.random=()=>roll;w.bombs[0].state='burning';w.hazards.explode(w.bombs[0]);}
function bag(w,n=3){for(const b of w.balls.slice(0,n)){w.resolveBead(b,'stolen');w.rival.bag.push(b);}}
test('a tiny central sand pillar cannot suspend a wide boulder',()=>{const w=new World(base({rocks:[{x:280,y:270,rx:75,ry:25}]}));w.terrain.grid.fill(0);for(let y=285;y<340;y+=2)for(let x=276;x<284;x+=2)w.terrain.grid[Math.floor(y/2)*280+Math.floor(x/2)]=1;for(let n=0;n<180;n++)w.hazards.step(1/120);a.ok(w.rocks[0].y>300);});
test('off-center support tilts the rock and geometry follows its angle',()=>{const w=new World(base({rocks:[{x:280,y:270,rx:75,ry:25}]}));w.terrain.grid.fill(0);for(let y=265;y<450;y+=2)for(let x=180;x<260;x+=2)w.terrain.grid[Math.floor(y/2)*280+Math.floor(x/2)]=1;for(let n=0;n<160;n++)w.hazards.step(1/120);const r=w.rocks[0];a.ok(r.angle>.1,JSON.stringify(r));const p=G.point(r,0,0);a.ok(G.contains(r,p.x,p.y));});
test('bomb is attached to the rotated rock, not its old axis aligned position',()=>{const w=new World(base({rocks:[{x:280,y:270,rx:75,ry:25,angle:.6}],bombs:[{rock:0,pad:{x:200,y:170}}]}));a.deepEqual(w.hazards.bombPoint(w.bombs[0]),G.point(w.rocks[0],75*.45,-25*.3));});
test('near thief drops actual bag contents after fear; far thief unaffected',()=>{const w=new World(base({rocks:[{x:280,y:270,rx:30,ry:25}],bombs:[{rock:0,pad:{x:200,y:170}}]}));Object.assign(w.rival,{x:420,y:270});bag(w);const originals=[...w.rival.bag];blast(w,.1);a.equal(w.rival.phase,'scared');for(let n=0;n<260;n++){w.rival.step(w,1/120);w.hazards.step(1/120);}a.equal(w.rival.bag.length,0);a.ok(originals.every(b=>b.active&&!b.stolen));a.equal(w.losses.stolen,0);const far=new World(base({rocks:[{x:80,y:270,rx:30,ry:25}],bombs:[{rock:0,pad:{x:80,y:170}}]}));Object.assign(far.rival,{x:480,y:100});blast(far,.1);a.equal(far.rival.fleeing,false);});
test('carry-away branch keeps bag until actual exit and no longer steals after leaving',()=>{const w=new World(base({rocks:[{x:280,y:270,rx:30,ry:25}],bombs:[{rock:0,pad:{x:200,y:170}}]}));Object.assign(w.rival,{x:420,y:270});bag(w,2);blast(w,.9);a.equal(w.rival.bag.length,2);for(let n=0;n<2400&&!w.rival.escaped;n++)w.rival.step(w,1/120);a.equal(w.rival.escaped,true);a.equal(w.rival.bag.length,0);const stolen=w.losses.stolen;for(let n=0;n<200;n++)w.rival.step(w,1/120);a.equal(w.losses.stolen,stolen);});
test('one operator is always scared; fleeing parks every cart for the round',()=>{const w=new World(base({rocks:[{x:80,y:120,rx:20,ry:20}],bombs:[{rock:0,pad:{x:80,y:80}}]}));blast(w,.1);a.equal(w.operator.phase,'scared');const x=w.jars[0].x;for(let n=0;n<1000;n++)w.crew.step(1/120);a.equal(w.operator.phase,'gone');a.equal(w.jars[0].x,x);const v=new World(base({rocks:[{x:80,y:120,rx:20,ry:20}],bombs:[{rock:0,pad:{x:80,y:80}}]}));blast(v,.9);for(let n=0;n<400;n++)v.crew.step(1/120);a.equal(v.operator.phase,'control');a.notEqual(v.jars[0].x,280);});
test('cart cap rejects invalid levels instead of hiding extra targets',()=>a.throws(()=>new World(base({jars:Array.from({length:5},(_,i)=>({x:60+i*100,color:'blue'}))})),/four|4/));
test('carried loot stays a pending opportunity until thief actually exits in World.step',()=>{const w=new World(base({groups:[{x:80,y:100,color:'blue',count:3}],targetScore:30,rocks:[{x:280,y:270,rx:30,ry:25}],bombs:[{rock:0,pad:{x:200,y:170}}]}));Object.assign(w.rival,{x:420,y:270});bag(w,3);blast(w,.9);w.checkOutcome();a.equal(w.state,'playing');a.equal(w.remainingPotential(),30);for(let n=0;n<2400&&w.state==='playing';n++)w.step();a.equal(w.rival.escaped,true);a.equal(w.state,'lost');a.equal(w.remainingPotential(),0);});
test('abandoned loot prevents premature exhaustion and counts original colors only',()=>{const w=new World(base({groups:[{x:80,y:100,color:'blue',count:3}],targetScore:30,rocks:[{x:280,y:270,rx:30,ry:25}],bombs:[{rock:0,pad:{x:200,y:170}}]}));Object.assign(w.rival,{x:420,y:270});bag(w,3);blast(w,.1);for(let n=0;n<140;n++)w.step();a.equal(w.state,'playing');a.equal(w.remainingPotential(),30);a.ok(w.droppedBags.some(b=>b.balls.length));});
test('rotated bead collision agrees with rotated terrain and leaves no old mask',()=>{const w=new World(base({rocks:[{x:280,y:270,rx:70,ry:20}]})),r=w.rocks[0];r.angle=Math.PI/2;w.terrain.rebuildRockMask(w.rocks);a.equal(w.terrain.rockMask[135*280+170],0);a.equal(w.terrain.rockMask[160*280+140],1);const b=w.balls[0];Object.assign(b,{x:280,y:320,vx:0,vy:50});w.collide(b);a.ok(!G.contains(r,b.x,b.y));});
test('blast fear radius is exactly 190 and does not retrigger fleeing/escaped thieves',()=>{for(const offset of [190,190.01]){const w=new World(base({rocks:[{x:280,y:270,rx:30,ry:25}],bombs:[{rock:0,pad:{x:200,y:170}}]})),p=w.hazards.bombPoint(w.bombs[0]);Object.assign(w.rival,{x:p.x-offset,y:p.y});blast(w,.9);a.equal(w.rival.fleeing,offset===190);if(w.rival.fleeing){const drop=w.rival.dropBag;w.random=()=>.1;w.rival.scare(w);a.equal(w.rival.dropBag,drop);w.rival.escaped=true;w.rival.scare(w);a.equal(w.rival.dropBag,drop);}}});
test('operator fear probability boundary and four cart brakes are deterministic',()=>{for(const roll of [.34999,.35]){const w=new World(base({jars:[{x:110,color:'blue'},{x:220,color:'blue'},{x:330,color:'blue'},{x:440,color:'blue'}],mechanics:{crewCount:4}}));w.random=()=>roll;w.crew.scare();a.equal(w.operator.flee,roll<.35);const before=w.jars.map(j=>j.x);for(let n=0;n<60;n++)w.crew.step(1/120);a.deepEqual(w.jars.map(j=>j.x),before);if(roll<.35){for(let n=0;n<1000;n++)w.crew.step(1/120);a.equal(w.operator.phase,'gone');a.deepEqual(w.jars.map(j=>j.x),before);const b=w.balls[0];w.receive(w.jars[0],b);a.equal(w.score,10);}}});
