const {test}=require('node:test');
const assert=require('node:assert/strict');
let api={};try{api=require('../engine.js');}catch(e){if(e.code!=='MODULE_NOT_FOUND')throw e;}
test('two independent stage simulations are available',()=>{assert.equal(typeof api.Adventure,'function');const g=new api.Adventure();assert.notEqual(g.stages[0].board,g.stages[1].board);assert.notEqual(g.stages[0].particles,g.stages[1].particles);g.stages[0].hp=12;assert.equal(g.stages[1].hp,100);});
test('a sealed board cannot collect weight and real pressure eventually hurts',()=>{assert.equal(typeof api.Adventure,'function');const g=new api.Adventure();g.start();for(let i=0;i<50*60&&g.phase!=='lost';i++)g.update(1/60);const a=g.stages[0];assert.equal(a.collected,0);assert.equal(a.gate,0);assert.equal(g.phase,'lost');assert.equal(a.hp,0);assert.ok(a.maxContact>0);});
test('pause freezes all physics and backstage B never runs',()=>{assert.equal(typeof api.Adventure,'function');const g=new api.Adventure();g.start();g.update(.05);g.paused=true;const before=JSON.stringify(g.snapshot());for(let i=0;i<100;i++)g.update(.05);assert.equal(JSON.stringify(g.snapshot()),before);assert.equal(g.stages[1].time,0);});
test('empty board alone is not victory, nor is an open gate without arrival',()=>{assert.equal(typeof api.Adventure,'function');const g=new api.Adventure();g.start();const a=g.stages[0];a.board.fill(null);g.update(.05);assert.equal(a.complete,false);a.gate=api.GATE_TRAVEL;a.latched=true;g.update(.05);assert.equal(a.complete,false);assert.equal(g.phase,'walking');});
test('restart B keeps A completion and restores only current stage',()=>{assert.equal(typeof api.Adventure,'function');const g=new api.Adventure();g.stages[0].complete=true;g.active=1;g.phase='lost';g.stages[1].hp=0;g.restart();assert.equal(g.active,1);assert.equal(g.stages[0].complete,true);assert.equal(g.stages[1].hp,100);assert.equal(g.stages[1].collected,0);assert.equal(g.phase,'ready');});
test('no shield contact means no pressure or damage',()=>{const s=new api.Stage(0);s.particles=[{id:0,x:100,y:100,r:7.1,vx:0,vy:0,angle:0,captured:false}];for(let i=0;i<180;i++)s.step();assert.equal(s.contact,0);assert.equal(s.force,0);assert.equal(s.shield.x,460);assert.equal(s.hp,100);});
test('weight credits actual bucket entry exactly once, not merely passing the board',()=>{const s=new api.Stage(0),p={id:0,x:240,y:760,r:7.1,vx:0,vy:0,angle:0,captured:false};s.particles=[p];s.step();assert.equal(s.collected,0);p.y=800;s.step();assert.equal(s.collected,1);for(let i=0;i<180;i++)s.step();assert.equal(s.collected,1);assert.equal(s.gate,0);});
test('two independent normal swaps and protected travel complete both stages',()=>{const g=new api.Adventure();for(let level=0;level<2;level++){g.start();const s=g.stages[level];assert.ok(g.swap(...s.hint()));for(let i=0;i<1200&&!s.latched;i++)g.update(1/60);assert.ok(s.latched);assert.ok(s.board.some(v=>v!==null));assert.equal(s.complete,false);assert.equal(s.gate,api.GATE_TRAVEL);assert.equal(s.particles.length,s.initial);assert.equal(new Set(s.particles.map(p=>p.id)).size,s.initial);assert.equal(s.collected,s.particles.filter(p=>p.captured).length);assert.equal(g.phase,'walking');let sawLift=false;for(let i=0;i<2400&&!['ready','won'].includes(g.phase);i++){g.update(1/60);if(g.entryLiftY>60&&g.entryLiftY<320){sawLift=true;assert.equal(g.actorY,g.entryLiftY);if(!g.paused){g.paused=true;const snap=JSON.stringify(g.snapshot());g.update(.08);assert.equal(JSON.stringify(g.snapshot()),snap);g.paused=false;}}}if(!level){assert.ok(sawLift);assert.equal(g.active,1);assert.equal(g.stages[1].time,0);assert.equal(g.entryLiftY,320);assert.equal(g.phase,'ready');}}assert.equal(g.phase,'won');assert.ok(g.stages.every(s=>s.complete&&s.hp>0));assert.ok(g.actorX-g.cameraX<650);});
test('mainline character reactions follow contact, hurt and calm without changing collision',()=>{const s=new api.Stage(0),x=s.shield.x;s.contact=2;assert.equal(s.characterFrame().sheet,'single');s.lastHurt=s.time;assert.equal(s.characterFrame().sheet,'hurt');s.time+=1;s.contact=0;assert.equal(s.characterFrame().sheet,'idle');assert.equal(s.shield.x,x);});
test('gate opening automatically carries the king through both rooms without an advance input',()=>{const g=new api.Adventure();for(let k=0;k<2;k++){g.start();assert.ok(g.swap(...g.stages[k].hint()));for(let i=0;i<1500&&g.phase==='playing';i++)g.update(1/60);assert.equal(g.phase,'walking');assert.equal(g.stages[k].complete,false);g.paused=true;const before=JSON.stringify(g.snapshot());g.update(.08);assert.equal(JSON.stringify(g.snapshot()),before);g.paused=false;for(let i=0;i<1800&&!['ready','won'].includes(g.phase);i++)g.update(1/60);if(!k){assert.equal(g.active,1);assert.equal(g.phase,'ready');assert.equal(g.stages[1].time,0);}}assert.equal(g.phase,'won');assert.ok(g.stages.every(s=>s.complete));});
test('clearing every brick also continues automatically, without any hidden action',()=>{const g=new api.Adventure();g.start();assert.ok(g.swap(6,7));while(g.stages[0].op)g.update(1/60);assert.ok(g.swap(...g.stages[0].hint()));while(g.stages[0].op)g.update(1/60);assert.ok(g.stages[0].board.every(v=>v==null));for(let i=0;i<1500&&g.active===0;i++)g.update(1/60);assert.equal(g.active,1);assert.equal(g.stages[0].complete,true);});

test('death takes priority over automatic departure when the gate is already latched',()=>{const g=new api.Adventure();g.start();g.stages[0].hp=0;g.stages[0].latched=true;g.update(.02);assert.equal(g.phase,'lost');assert.equal(g.stages[0].complete,false);});
