async (page) => {
 const base=page.url().split('?')[0],errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.setViewportSize({width:1440,height:1050});await page.goto(base);await page.locator('#start').click();
 const click=async(p,i,touch=false)=>{const b=await p.locator('#game').boundingBox(),x=b.x+(24+(i%8+.5)*48)*b.width/432,y=b.y+(398+(Math.floor(i/8)+.5)*48)*b.height/780;if(touch)await p.touchscreen.tap(x,y);else await p.mouse.click(x,y);};
 await page.locator('#pause').click();const before=await page.evaluate(()=>kingGame.snapshot());await page.waitForTimeout(350);const after=await page.evaluate(()=>kingGame.snapshot());if(before.time!==after.time||!after.paused)throw Error('Pause drift');await page.locator('#resume').click();
 const n=await page.evaluate(()=>kingGame.snapshot().moves);const b=await page.locator('#game').boundingBox();await page.mouse.click(b.x+30,b.y+30);if(await page.evaluate(()=>kingGame.snapshot().moves)!==n)throw Error('Invalid click costs move');
 for(const i of [54,46,38,30,22,14,6]){await click(page,i);await page.waitForTimeout(160);}
 await page.waitForFunction(()=>kingGame.snapshot().state==='won',null,{timeout:25000});const first=await page.evaluate(()=>kingGame.snapshot());await page.screenshot({path:'output/desktop-win.png',fullPage:true});
 await page.locator('#result-next').click();await page.locator('#start').click();for(const i of [52,44,36,28,20,22,14,6]){await click(page,i);await page.waitForTimeout(200);}await page.waitForFunction(()=>kingGame.snapshot().state==='won',null,{timeout:25000});const second=await page.evaluate(()=>kingGame.snapshot());await page.screenshot({path:'output/second-win.png',fullPage:true});
 const context=await page.context().browser().newContext({viewport:{width:390,height:844},deviceScaleFactor:2,isMobile:true,hasTouch:true});const mobile=await context.newPage();await mobile.goto(base);await mobile.locator('#start').click();for(const i of [54,46,38,30,22,14,6]){await click(mobile,i,true);await mobile.waitForTimeout(180);}await mobile.waitForFunction(()=>kingGame.snapshot().state==='won',null,{timeout:25000});const phone=await mobile.evaluate(()=>({state:kingGame.snapshot().state,controlsBottom:document.querySelector('.controls').getBoundingClientRect().bottom,width:innerWidth,height:innerHeight,tile:document.querySelector('canvas').getBoundingClientRect().width*48/432}));if(phone.controlsBottom>844||phone.tile<36)throw Error('Mobile layout '+JSON.stringify(phone));await mobile.screenshot({path:'output/touch-win.png',fullPage:true});await mobile.reload();const reset=await mobile.evaluate(()=>kingGame.snapshot());if(reset.level!==1||reset.state!=='ready'||reset.collected!==0)throw Error('Refresh does not reset');await context.close();if(errors.length)throw Error(errors.join('\n'));return {first,second,phone,errors};
}
