async (page) => {
 const base=page.url(),errors=[],sequences=[[[10,18],[14,15],[38,39],[44,45],[40,41],[42,50],[42,43],[41,49]],[[16,17],[34,35],[12,13],[14,15],[40,41],[42,43],[44,45],[46,47]]];page.on('pageerror',e=>errors.push(e.message));
 const snapshot=(p,geometry=false)=>p.evaluate(g=>kingGame.snapshot({geometry:g}),geometry);
 const point=async(p,i)=>{const b=await p.locator('#game').boundingBox();return{x:b.x+(24+(i%8+.5)*48)*b.width/432,y:b.y+(398+(Math.floor(i/8)+.5)*48)*b.height/780};};
 const click=async(p,i,touch=false)=>{const q=await point(p,i);if(touch)await p.touchscreen.tap(q.x,q.y);else await p.mouse.click(q.x,q.y);};
 const swap=async(p,a,b,touch=false)=>{await click(p,a,touch);await click(p,b,touch);await p.waitForFunction(()=>!kingGame.snapshot().phase,null,{timeout:15000});};
 await page.setViewportSize({width:1440,height:1050});await page.goto(base);await page.locator('#start').click();await page.waitForFunction(()=>kingGame.snapshot().time>5);await page.screenshot({path:'output/v4/desktop-pressure.png'});const pressure=await snapshot(page,true);if(pressure.geometry.maxOverlap>.05)throw Error('Solid overlap');
 for(const [a,b]of sequences[0].slice(0,-1))await swap(page,a,b);const lastGem=await snapshot(page);await page.waitForFunction(t=>kingGame.snapshot().time>t+5,lastGem.time);const stillPlaying=await snapshot(page,true);if(stillPlaying.state!=='playing'||!stillPlaying.remaining||stillPlaying.geometry.maxOverlap>.05)throw Error('Premature win or overlap');await page.screenshot({path:'output/v4/gems-not-gold-goal.png'});
 await swap(page,...sequences[0].at(-1));await page.waitForFunction(()=>kingGame.snapshot().state==='won');const first=await snapshot(page);if(first.remaining!==0)throw Error('Not cleared');await page.screenshot({path:'output/v4/desktop-clear.png'});
 await page.locator('#result-next').click();await page.locator('#start').click();for(const [a,b]of sequences[1])await swap(page,a,b);await page.waitForFunction(()=>kingGame.snapshot().state==='won');const second=await snapshot(page);if(second.remaining!==0)throw Error('Beam counted as gem');
 const context=await page.context().browser().newContext({viewport:{width:390,height:844},deviceScaleFactor:2,isMobile:true,hasTouch:true});const mobile=await context.newPage();mobile.on('pageerror',e=>errors.push(e.message));await mobile.goto(base);await mobile.locator('#start').click();await click(mobile,sequences[0][0][0],true);await click(mobile,sequences[0][0][1],true);await mobile.waitForFunction(()=>kingGame.snapshot().phase?.kind==='fall');await mobile.locator('#pause').click();const frozen=await snapshot(mobile);await mobile.waitForTimeout(600);const frozenAfter=await snapshot(mobile);if(frozen.time!==frozenAfter.time||JSON.stringify(frozen.falling)!==JSON.stringify(frozenAfter.falling))throw Error('Pause drifts');await mobile.locator('#resume').click();await mobile.waitForFunction(()=>!kingGame.snapshot().phase);
 for(const [a,b]of sequences[0].slice(1))await swap(mobile,a,b,true);await mobile.waitForFunction(()=>kingGame.snapshot().state==='won');const phone=await snapshot(mobile);const layout=await mobile.evaluate(()=>({bottom:document.querySelector('.controls').getBoundingClientRect().bottom,tile:document.querySelector('#game').getBoundingClientRect().width*48/432,width:innerWidth}));if(layout.bottom>844||layout.tile<36||layout.width!==390)throw Error('Mobile layout');await mobile.screenshot({path:'output/v4/touch-clear.png'});
 await mobile.locator('#result-next').click();await mobile.locator('#start').click();for(const [a,b]of sequences[1])await swap(mobile,a,b,true);await mobile.waitForFunction(()=>kingGame.snapshot().state==='won');const phoneSecond=await snapshot(mobile);await mobile.reload();await mobile.locator('#start:enabled').waitFor();const reset=await snapshot(mobile);if(reset.hp!==100||reset.remaining!==56||reset.rallies||reset.state!=='ready')throw Error('Refresh reset');await context.close();if(errors.length)throw Error(errors.join('\n'));
 return{pressure:{...pressure,geometry:{maxOverlap:pressure.geometry.maxOverlap}},stillPlaying:{...stillPlaying,geometry:{maxOverlap:stillPlaying.geometry.maxOverlap}},first,second,phone,phoneSecond,layout,errors};
}
