async (page) => {
 const base=page.url(),errors=[],sequences=[[[26,34],[48,49],[44,45]],[[12,13],[45,53],[6,7],[52,53],[43,51]]];page.on('pageerror',e=>errors.push(e.message));
 const snapshot=p=>p.evaluate(()=>kingGame.snapshot());
 const point=async(p,i)=>{const b=await p.locator('#game').boundingBox();return{x:b.x+(24+(i%8+.5)*48)*b.width/432,y:b.y+(398+(Math.floor(i/8)+.5)*48)*b.height/780};};
 const click=async(p,i,touch=false)=>{const q=await point(p,i);if(touch)await p.touchscreen.tap(q.x,q.y);else await p.mouse.click(q.x,q.y);};
 const swap=async(p,a,b,touch=false)=>{await click(p,a,touch);await click(p,b,touch);await p.waitForFunction(()=>!kingGame.snapshot().phase,null,{timeout:15000});};
 await page.setViewportSize({width:1440,height:1050});await page.goto(base);await page.locator('#start').click();
 await page.locator('#pause').click();const before=await snapshot(page);await page.waitForTimeout(350);const after=await snapshot(page);if(before.time!==after.time||before.hp!==after.hp||!after.paused)throw Error('Pause drift');await page.locator('#resume').click();
 await swap(page,4,5);const invalid=await snapshot(page);if(invalid.actions||invalid.board.some(v=>v===null))throw Error('Pair disappeared');
 // Open the lower chamber first, wait for a real hit, then finish the route.
 for(const [a,b]of sequences[0].slice(0,-1))await swap(page,a,b);
 await page.waitForFunction(()=>kingGame.snapshot().hp<100,null,{timeout:70000});const wounded=await snapshot(page);if(wounded.hp!==88||wounded.state!=='playing')throw Error('First touch should survive');await page.screenshot({path:'output/v3-first-hit.png'});
 const [a,b]=sequences[0].at(-1),pa=await point(page,a),pb=await point(page,b);await page.mouse.move(pa.x,pa.y);await page.mouse.down();await page.mouse.move(pb.x,pb.y,{steps:5});await page.mouse.up();
 await page.waitForFunction(()=>kingGame.snapshot().phase?.kind==='fall');const falling=await snapshot(page);await page.screenshot({path:'output/v3-falling.png'});await click(page,0);await click(page,1);if((await snapshot(page)).actions!==3)throw Error('Input during fall');
 await page.waitForFunction(()=>kingGame.snapshot().clearance>.5,null,{timeout:20000});const released=await snapshot(page);await page.waitForFunction(t=>kingGame.snapshot().time>=t+2,released.time,{timeout:12000});const stopped=await snapshot(page);if(stopped.hp!==released.hp||stopped.hp<=0)throw Error('Damage continued after release');
 await page.waitForFunction(()=>kingGame.snapshot().state==='won',null,{timeout:40000});const first=await snapshot(page);await page.screenshot({path:'output/v3-desktop-rescue.png'});
 await page.locator('#result-next').click();await page.locator('#start').click();for(const [a,b]of sequences[1])await swap(page,a,b);await page.waitForFunction(()=>kingGame.snapshot().state==='won',null,{timeout:55000});const second=await snapshot(page);await page.screenshot({path:'output/v3-second-win.png'});
 const context=await page.context().browser().newContext({viewport:{width:390,height:844},deviceScaleFactor:2,isMobile:true,hasTouch:true});const mobile=await context.newPage();mobile.on('pageerror',e=>errors.push(e.message));await mobile.goto(base);await mobile.locator('#start').click();for(const [a,b]of sequences[0])await swap(mobile,a,b,true);await mobile.waitForFunction(()=>kingGame.snapshot().state==='won',null,{timeout:55000});const phone=await mobile.evaluate(()=>({state:kingGame.snapshot().state,hp:kingGame.snapshot().hp,controlsBottom:document.querySelector('.controls').getBoundingClientRect().bottom,width:innerWidth,height:innerHeight,tile:document.querySelector('canvas').getBoundingClientRect().width*48/432}));if(phone.controlsBottom>844||phone.tile<36)throw Error('Mobile layout '+JSON.stringify(phone));await mobile.screenshot({path:'output/v3-touch-win.png'});
 await mobile.reload();await mobile.locator('#start').waitFor({state:'visible'});const reset=await snapshot(mobile);if(reset.level!==1||reset.state!=='ready'||reset.hp!==100||reset.collected!==0)throw Error('Refresh reset');await mobile.locator('#start').click();await mobile.locator('#remix').click();if((await snapshot(mobile)).remixes!==1)throw Error('Remix');await mobile.locator('#restart').click();if((await snapshot(mobile)).state!=='ready')throw Error('Restart');
 await mobile.locator('#choose-level').click();await mobile.locator('#level-dialog [data-level="1"]').click();await mobile.locator('#start').click();for(const [a,b]of sequences[1])await swap(mobile,a,b,true);await mobile.waitForFunction(()=>kingGame.snapshot().state==='won',null,{timeout:55000});const phoneSecond=await snapshot(mobile);
 await context.close();if(errors.length)throw Error(errors.join('\n'));return{wounded,falling,released,stopped,first,second,phone,phoneSecond,errors};
}
