const {test}=require('node:test'),assert=require('node:assert/strict'),{Game}=require('../engine.js'),M=require('../match.js');
function sealed(){const g=new Game(0,{rallySeed:1});g.start();g.time=4;g.hp=76;g.particles=[{id:0,x:48,y:679,r:7,vx:0,vy:0,angle:0,spin:0}];g.spawned=g.supplied=1;g.collected=g.queued=0;g.sourceEnabled=false;const after=Array(56).fill(null);after[40]=0;after[48]=1;after[41]=2;g.operation={kind:'fall',started:0,progressAt:0,progressTravel:0,after,matched:[],tiles:[{from:32,to:40,color:0,x:24,startY:624,y:624,targetY:638},{from:48,to:48,color:1,x:24,startY:686,y:686,targetY:686},{from:41,to:41,color:2,x:72,startY:638,y:638,targetY:638}]};
// A separate supported six-gem pair of columns retains a real legal exchange,
// so this fixture continues to test restored input instead of terminal victory.
for(const [i,color]of [[35,0],[36,1],[43,1],[44,0],[51,0],[52,1]]){after[i]=color;const y=398+Math.floor(i/8)*48;g.operation.tiles.push({from:i,to:i,color,x:24+i%8*48,startY:y,y,targetY:y});}return g;}
function conserved(g){assert.equal(g.spawned,g.particles.length+g.collected+g.crushed);assert.equal(new Set(g.particles.map(p=>p.id)).size,g.particles.length);assert.equal(g.supplied,g.spawned+g.queued);assert.ok(g.overlap()<.05);}
test('an internal settling stall must never defeat a living king',()=>{const g=sealed();g.update(1/120);assert.equal(g.state,'playing');assert.equal(g.hp,76);assert.notEqual(g.reason,'jam');assert.ok(g.recovery);});
test('sealed recovery crushes only after sustained clamp, settles and accepts input',()=>{const g=sealed();g.update(1/120);const start=g.time,actions=g.actions,remixes=g.remixes;let ticks=0;while(g.recovery){assert.ok(ticks++<300);g.update(1/120);assert.equal(g.time,start);assert.equal(g.hp,76);assert.equal(g.actions,actions);assert.equal(g.remixes,remixes);conserved(g);if(g.mechanicalTime<.05)assert.equal(g.crushed,0);}assert.equal(g.crushed,1);assert.equal(g.collected,0);assert.equal(g.operation,null);assert.equal(M.remaining(g.board),9);assert.equal(g.state,'playing');assert.ok(g.swap(43,44));});
test('low HP, spike cooldown and active rally stay frozen throughout exclusive recovery',()=>{const g=sealed();g.hp=16;g.nextDamageAt=g.time+.01;g.rallyUntil=g.time+1;g.rallyCooldown=g.time+8;g.beginRecovery();const before=[g.time,g.hp,g.nextDamageAt,g.rallyUntil,g.rallyCooldown,g.shield.x];let ticks=0;while(g.recovery){assert.ok(ticks++<300);g.update(1/120);}assert.deepEqual([g.time,g.hp,g.nextDamageAt,g.rallyUntil,g.rallyCooldown,g.shield.x],before);assert.ok(g.mechanicalTime>=.05);});
test('flowing gold counts only after the whole radius crosses the outlet',()=>{const g=sealed();g.operation=null;g.recovery=null;g.particles[0].y=760;g.update(1/120);assert.equal(g.collected,0);g.particles[0].vy=570;g.update(1/120);assert.equal(g.collected,1);assert.equal(g.crushed,0);conserved(g);});
test('an open slow side route preserves its gold during prolonged settling',()=>{const g=sealed();g.operation.tiles=g.operation.tiles.filter(t=>t.from!==41);g.operation.after[41]=null;g.beginRecovery();for(let i=0;i<600&&g.operation;i++){g.update(1/120);conserved(g);assert.equal(g.crushed,0);}assert.equal(g.operation,null);assert.equal(g.spawned,g.particles.length+g.collected+g.crushed);});
test('maximum gravity distance with an open outlet retains falling gold',()=>{for(const stone of [false,true]){const g=sealed();g.operation={kind:'fall',started:0,matched:[],after:Array(56).fill(null),tiles:[{from:0,to:48,color:0,x:24,startY:398,y:398,targetY:686}]};g.operation.after[48]=0;if(stone)g.particles[0].y=500;else{g.particles=[];g.spawned=g.supplied=0;}g.beginRecovery();let ticks=0;while(g.recovery){g.update(1/120);conserved(g);assert.ok(++ticks<360);}assert.equal(g.crushed,0);assert.equal(g.operation,null);assert.equal(g.board[48],0);}});
test('capacity backpressure preserves queued supply without deleting crowded grains',()=>{const g=new Game(0);g.start();g.particles=Array.from({length:1600},(_,id)=>({id,x:200,y:500,r:7}));g.spawned=g.supplied=1600;g.queued=0;g.spawnClock=2;g.emit();assert.equal(g.particles.length,1600);assert.ok(g.queued>=2);assert.equal(g.supplied,g.spawned+g.queued);assert.equal(g.spawned,g.particles.length+g.collected+g.crushed);});
