const {test}=require('node:test'),assert=require('node:assert/strict'),{Game}=require('../engine.js'),M=require('../match.js');
const tail=()=>{const b=Array(56).fill(null);b[48]=3;b[52]=0;b[46]=1;b[54]=2;return b;};
function game(board){const g=new Game(0);g.start();g.board=board;g.hp=28;return g;}
test('the four distinct screenshot leftovers pass automatically without erasing gems or spending remix',()=>{const b=tail(),g=game(b);assert.equal(M.legal(b).length,0);g.update(1/120);assert.equal(g.state,'won');assert.equal(g.reason,'no-moves');assert.equal(g.snapshot().remaining,4);assert.deepEqual(g.board,b);assert.equal(g.hp,28);assert.equal(g.remixes,2);assert.equal(g.sourceEnabled,false);const t=g.time;g.update(.1);assert.equal(g.time,t);assert.equal(g.hp,28);});
test('a one or two gem tail passes; zero gems retains a full-clear outcome',()=>{for(let n=0;n<=2;n++){const b=Array(56).fill(null);for(let i=0;i<n;i++)b[48+i]=i;const g=game(b);g.update(1/120);assert.equal(g.state,'won');assert.equal(g.reason,n?'no-moves':'cleared');assert.equal(g.snapshot().remaining,n);}});
test('having a legal match keeps playing even if a full-clear solver finds no solution',()=>{const b=Array(56).fill(null);[b[40],b[41],b[42],b[48],b[49],b[50]]=[0,1,0,1,0,1];b[55]=3;const g=game(b);assert.ok(M.legal(b).length);assert.equal(M.solveClear(b),null);g.update(1/120);assert.equal(g.state,'playing');assert.equal(g.sourceEnabled,true);});
test('existing automatic triples resolve before a no-move outcome',()=>{const b=Array(56).fill(null);b[48]=b[49]=b[50]=0;const g=game(b);assert.equal(M.legal(b).length,0);g.update(1/120);assert.equal(g.state,'playing');assert.equal(g.operation.kind,'cascade');while(g.operation&&g.state==='playing')g.update(1/120);assert.equal(g.state,'won');assert.equal(g.snapshot().remaining,0);assert.equal(g.reason,'cleared');});
test('an in-progress fall cannot pass based on a temporary unplayable board',()=>{const b=tail();b[0]=b[48];b[48]=null;const g=game(b);g.beginFall();g.update(1/120);assert.equal(g.state,'playing');assert.ok(g.operation);let ticks=0;while(g.operation&&g.state==='playing'){assert.ok(ticks++<1200);g.update(1/120);}assert.equal(g.state,'won');assert.equal(g.reason,'no-moves');assert.deepEqual(g.board,tail());});
test('fatal spike contact still takes precedence over an unplayable tail',()=>{const g=game(tail());g.hp=12;g.shield.x=226;g.shield.vx=-1.8;g.contactForce=1000;g.rallyRandom=()=>0;g.update(1/120);assert.equal(g.state,'lost');assert.equal(g.reason,'hp');assert.equal(g.hp,0);});
